apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "metrics-server-exporter.fullname" . }}
  labels:
{{ include "metrics-server-exporter.labels" . | indent 4 }}
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics-server-exporter.fullname" . }}
  namespace: {{ include "metrics-server-exporter.namespace" . }}
  labels:
{{ include "metrics-server-exporter.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metrics-server-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ include "metrics-server-exporter.namespace" . }}
  name: {{ include "metrics-server-exporter.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "metrics-server-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
