apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-server-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "metrics-server-exporter.labels" . | indent 4 }}
{{- if .Values.serviceAnnotations }}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "metrics-server-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
