apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: platform
  name: metrics-server-exporter
  labels:
    app: metrics-server-exporter
    product: platform
    process: exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metrics-server-exporter
        product: platform
        process: exporter
    spec:
      serviceAccountName: metrics-server-exporter
      containers:
      - name: metrics-server-exporter
        image: deadc/metrics-server-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 150Mi
              cpu: 100m
      restartPolicy: Always
