apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-permissions-metrics-server-exporter.yaml
- 10-deployment-metrics-server-exporter.yaml
- 20-service-metrics-server-exporter.yaml
