---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metrics-server-exporter
  labels:
    k8s-app: metrics-server-exporter
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server-exporter
  labels:
    k8s-app: metrics-server-exporter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: metrics-server-exporter
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: metrics-server-exporter
roleRef:
  kind: ClusterRole
  name: metrics-server-exporter
  apiGroup: rbac.authorization.k8s.io
