apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  name: metrics-server-exporter
  labels:
    k8s-app: metrics-server-exporter
spec:
  ports:
  - port: 9104
    protocol: TCP
    targetPort: 8000
  selector:
    k8s-app: metrics-server-exporter
