name: Blackbox

on:
  repository_dispatch:
    types: [event-trigger]
  workflow_dispatch: ~

# .github/workflows/blackbox-workflow.yml
jobs:
    run-blackbox-action:
        runs-on: [self-hosted, tech-radar]
        steps:
            - uses: actions/checkout@v3
              with:
                ref: '${{ github.event.repository.default_branch }}'
                fetch-depth: 0
            - id: blackbox
              uses: olxbr/blackbox-action@v1
              with:
                config: ${{ secrets.BLACK_BOX_CONFIG }}
              env:
                DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
                REPO_NAME: ${{ github.event.repository.name }}
                DOCKER_ECR_PASSWORD: ${{ secrets.DOCKER_ECR_PASSWORD }}
                DOCKER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY_HOST }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
                LOGLEVEL: 'INFO'
