name: Release
on: release
jobs:

  publish:
    name: publish
    runs-on: ubuntu-20.04
    
    steps:
      - name: "Get release name"
        id: "release-name"
        run: "echo \"::set-output name=release::${GITHUB_REF##*/}\""
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore docker cache
        uses: actions/cache@v2
        with:
          path: ~/docker-cache-final-image
          key: metrics-server-exporter-docker-final-image-${{ github.sha }}
          restore-keys: |
            metrics-server-exporter-docker-final-image-${{ github.sha }}